[metadata]
name = myce_student_transactions
version = 0.0.2
description = MyCE student transactions app
url = https://www.canusia.com/
author = Avinash Kadaji
author_email = avi@canusia.com
classifiers =
    Environment :: Web Environment
    Framework :: Django
    Programming Language :: Python :: 3

[options]
include_package_data = true
packages = find:
python_requires = >=3.8
install_requires =
    Django >= 4.2
