# Generated by Django 4.2 on 2024-04-20 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cis', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('t_type', models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10)),
                ('amount', models.FloatField(default=0.0)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cis.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cis.term')),
            ],
        ),
    ]
